version: '2'
services:
  thingsboard-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
    - '9090'
    volumes:
    - thingsboard-gateway-conf:/etc/tb-gateway/conf
    - thingsboard-gateway-log:/var/log/tb-gateway
    environment:
    - GATEWAY_ACCESS_TOKEN=${GATEWAY_ACCESS_TOKEN}
    - GATEWAY_HOST=${GATEWAY_HOST}
volumes:
  thingsboard-gateway-conf:
    driver: local
    driver_opts:
      type: none
      device: /data/thingsboard-gateway-conf
      o: bind
  thingsboard-gateway-log:
    driver: local
    driver_opts:
      type: none
      device: /data/thingsboard-gateway-log
      o: bind
